name: Prep for Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    # Job name is
    name: Verify, Bump Version, and Tag for Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[automated release]')"
    steps:
      - uses: actions/checkout@v2
      - name: Print ref
        run: echo $GITHUB_REF
      - name: Bump version
        run: |
          git config --global user.name "test-auto-user"
          git config --global user.email "test-auto-user"
          npm version major -m "Releasing %s [automated release]"
      - name: Push
        run: git push --tags origin master

        